# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'

chef_configuration = JSON.parse(Pathname(__FILE__).dirname.join('.', 'chef.json').read)

Vagrant.configure("2") do |config|
  config.berkshelf.enabled = true
  config.omnibus.chef_version = :latest
  config.vm.box = "chef/ubuntu-14.04"
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 2048]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
  config.ssh.forward_agent = true
  config.vm.network :forwarded_port, guest: 4200, host: 4200, auto_correct: true # Ember Server
  config.vm.network :forwarded_port, guest: 35729, host: 35729, auto_correct: true # Live Reload
  config.vm.synced_folder '~/.ssh/', '/ssh/'
  config.vm.provision :shell, :path => 'configure.sh'
  config.vm.provision :chef_solo do |chef|
    chef.json = chef_configuration
  end
end
